version: "3"
services: 
  postgres:
    image: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=my-fotolibro-db
    ports:
      - 54321:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
  my-fotolibro-backend:
    container_name: my_fotolibro_backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - ${EXPRESS_PORTS}
